"""change timestamp Date to DateTime

Revision ID: a235af8a57bc
Revises: af01069a1484
Create Date: 2025-12-22 19:23:59.516788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a235af8a57bc'
down_revision: Union[str, Sequence[str], None] = 'af01069a1484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'timestamp',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_comment='UTC Timestamp of when the account was created.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_comment='UTC Timestamp of when the account was created.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
