"""Added unique to username and email and timestamp + some documentation

Revision ID: af01069a1484
Revises: bf01125131e1
Create Date: 2025-12-22 18:45:02.295275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af01069a1484'
down_revision: Union[str, Sequence[str], None] = 'bf01125131e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('timestamp', sa.Date(), server_default=sa.text('now()'), nullable=False, comment='UTC Timestamp of when the account was created.'))
    op.alter_column('user', 'id',
               existing_type=sa.INTEGER(),
               comment='Unique identifier for the user (Auto-incrementing PK).',
               existing_comment='cest quoi un comment sur une collone d`une table',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=40),
               nullable=False,
               comment='Unique display name. Used for public profile URLs and mentions.')
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=70),
               nullable=False,
               comment='Primary contact email. Must be unique and verified for login.')
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False,
               comment='Werkzeug hash (scrypt:32768:8:1). Use check_password_hash to verify.')
    op.create_unique_constraint(op.f('uq_user_email'), 'user', ['email'])
    op.create_unique_constraint(op.f('uq_user_username'), 'user', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_username'), 'user', type_='unique')
    op.drop_constraint(op.f('uq_user_email'), 'user', type_='unique')
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True,
               comment=None,
               existing_comment='Werkzeug hash (scrypt:32768:8:1). Use check_password_hash to verify.')
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=70),
               nullable=True,
               comment=None,
               existing_comment='Primary contact email. Must be unique and verified for login.')
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=40),
               nullable=True,
               comment=None,
               existing_comment='Unique display name. Used for public profile URLs and mentions.')
    op.alter_column('user', 'id',
               existing_type=sa.INTEGER(),
               comment='cest quoi un comment sur une collone d`une table',
               existing_comment='Unique identifier for the user (Auto-incrementing PK).',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('user', 'timestamp')
    # ### end Alembic commands ###
